NAME = SBQueue
TYPE = APP
SRCS = BackupQueue.cpp
LIBS = be
OPTIMIZE = FULL 
RDEFS = SBQueue.rdef
OBJ_DIR = _objects
TARGET_DIR = ../..

DEVEL_DIRECTORY := \
	$(shell findpaths -r "makefile_engine" B_FIND_PATH_DEVELOP_DIRECTORY)
include $(DEVEL_DIRECTORY)/etc/makefile-engine


